name: Mysql actions demo
run-name: ${{ github.actor }} is testing out Mysql GitHub Actions 🚀
on: [push]
jobs:
  setup_mysql_database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Secret5555
          MYSQL_DATABASE: flyway_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" -u"root" -p"Secret5555" --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Deploy to Database
        env:
          DB_HOST: ${{ secrets.DB_HOST || '127.0.0.1' }}
          DB_USER: ${{ secrets.DB_ADMIN_USER || 'root' }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD  || 'Secret5555'}}
          DB_NAME: ${{ secrets.DB_NAME || 'flyway_test' }}
        run: mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < schema_changes.sql
      - name: pull flyway
        run: docker pull redgate/flyway
      - name: Run initial migrations
        env:
          DB_HOST: ${{ secrets.DB_HOST || '127.0.0.1' }}
          DB_USER: ${{ secrets.DB_ADMIN_USER || 'root' }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD  || 'Secret5555'}}
        run: docker run --rm --network="host" -v "${{ github.workspace }}/migrations:/flyway/sql" redgate/flyway -user=$DB_USER -password=$DB_PASSWORD -url=jdbc:mysql://$DB_HOST:3306/flyway_test?allowPublicKeyRetrieval=true&useSSL=false migrate

      - name: Run subscriber incremental migrations
        env:
          DB_HOST: ${{ secrets.DB_HOST || '127.0.0.1' }}
          SUBSCRIBER_USER: ${{ secrets.SUBSCRIBER_USER || 'subscriber_user' }}
          SUBSCRIBER_PASSWORD: ${{ secrets.SUBSCRIBER_PASSWORD || 'SubscriberPass123' }}
        run: docker run --rm --network="host" -v "${{ github.workspace }}/subscriber_migrations:/flyway/sql" redgate/flyway -user=$SUBSCRIBER_USER -password=$SUBSCRIBER_PASSWORD -url=jdbc:mysql://$DB_HOST:3306/subscriber_db migrate

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CRUD tests
        env:
          DB_HOST: ${{ secrets.DB_HOST || '127.0.0.1' }}
          SUBSCRIBER_USER: ${{ secrets.SUBSCRIBER_USER || 'subscriber_user' }}
          SUBSCRIBER_PASSWORD: ${{ secrets.SUBSCRIBER_PASSWORD || 'SubscriberPass123' }}
        run: python -m pytest tests/ -v

      - name: Deployment Complete
        run: |
          echo "🚀 Deployment Successfully Completed!"
          echo "✅ Database migrations applied"
          echo "✅ Subscriber system deployed"
          echo "✅ All CRUD tests passed"
          echo "📅 Deployment completed at: $(date)"
          echo "🎉 System ready for use!"
